### ISSUE TITLE
Missing events on concurrent access

### ISSUE THREAD

**Issue by nouchka** [segmentio/analytics-php#125]
Hello,

I'm using this library with Magento2 module and we have seen some events missing in the log.
There is no lock mechanism to prevent the analytics.logs file been at the same time written with a new event and been renamed by the send.php cron.
I have reproduced the case adding some delay between the initialization with the fopen in the construct of File.php and the function to write in the file; launching the cron during this delay. Cron renamed the file and the write function didn't recreate the file as there is no more fopen.

First solution could be the add a fopen in the File.php write function in case of the file is missing. It will recreate the log for the new event. And reduce the chance to have concurrent action.
Second solution could be to write in a file named with a timestamp and to use send.php on file at least one minute old

**Comment by nd4p90x** [comment]
Sorry for the prolonged delay in responding to you.  I understand what your issue is, however, I am curious as to the process that is renaming a file that is opened by another process and is currently in use.  If you could please provide me with the OS details and the section of the cron script that renames the in-use file, I could continue with my investigation and resolution.  Thank you.

**Comment by nd4p90x** [comment]
If you are still having issues with this process, please feel free to re-open this ticket and I will be happy to assist as best I can.
