### ISSUE TITLE
Not working with laravel `queue:work` command

### ISSUE THREAD

**Issue by sherryt400** [segmentio/analytics-php#126]
It was working perfectly in the local environment because we are using `queue:listen` command but on production, it's not working with `queue:work` command 
And I did test locally with both commands same on local i.e. works with `queue:listen` but not with `queue:work`
no error, nothing

**Comment by nd4p90x** [comment]
@sherryt400 Thank you for your posted issue.  I know it has been some time since you posted this, but before I responded I tested on my local as well.  Using Laravel 8.40 & PHP 7.4.16, I was able to create a job that posts to the Segment.io API and using both the queue:listen and queue:work my job executes and reports correctly.  If this is still an issue for you, please provide more information about your environment and I will be happy to explore this further with you.  Thank you.

**Comment by alexhansonsmith** [comment]
Hi @sherryt400 - I am experiencing the same issue, it works with queue:listen but not with queue:work. Did you manage to find a workaround?

**Comment by baj84** [comment]
@sherryt400 Did you fix this? I'm having a similar issue.
