### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by MatanYadaev** [segmentio/analytics-php#152]

**Comment by nd4p90x** [comment]
Working on implementing testing for PHP8 to confirm compatibility.  Thank you.

**Comment by MatanYadaev** [comment]
@nd4p90x Any estimation? Does this task is really in progress? PHP 8 released 4 months ago.

**Comment by nd4p90x** [comment]
@MatanYadaev thanks for the question.  I expect the php 8 compatibility upgrade to be by the end of the month.  There are other items we are focusing on currently and the upgrade path isn't as cut and dried as I thought it might be when I started the new branch.  I will keep this thread updated.  Thanks.

**Comment by aryehbeitz** [comment]
@nd4p90x good to know it's upcoming. we're also waiting for this - blocking our upgrade to php 8

**Comment by smartens80** [comment]
Any further updates on when PHP 8.0 will be supported?

**Comment by FutureFutureTo** [comment]
any idea on whats going on with this?

**Comment by smartens80** [comment]
> any idea on whats going on with this?

Project not dead - last commit was 21 days ago... why not focus on this? PHP v8 support is pretty important IMHO!

**Comment by nd4p90x** [comment]
Morning everyone, this is an active issue and it is currently being worked on.  Our hope is to have it ready for testing in the next week.  Apologies for the delay, this is very important to us as well.  Thank you.

**Comment by FutureFutureTo** [comment]
This is honestly super frustrating.

'Our PHP library lets you record analytics data from your PHP code. The requests hit our servers, and then we route your data to any analytics service you enable on your destinations page.'

So this is Segment's proprietary library? The same Segment that we pay money for each month to basically not use at this point because they won't allocate adequate time/resources to update this library to PHP8?

At the very least, how do we get access to the low level API server side?

We're going to have to bail on Segment entirely at this point. The client side API is blocked by a lot of pop up blockers and straight up browsers now. Server side is the only thing left, and well, it seems to be just ignored?

**Comment by nd4p90x** [comment]
@FutureFutureTo Sorry to hear about your frustrations, did you not see that we released the [latest version](https://github.com/segmentio/analytics-php/pull/181) with PHP 8 support last week?  Is there an issue with the release that we need to be aware of?  I would be happy to assist you with any issues you may be having.
https://packagist.org/packages/segmentio/analytics-php

**Comment by FutureFutureTo** [comment]
@nd4p90x Thanks for the quick response - I did not see that, no. It's not tagged though, is that a plan in the near future?

**Comment by nd4p90x** [comment]
@FutureFutureTo Thanks for the info.  I did not realize the tag for the latest release is not attached to 2.0.  We will get that resolved today.  Thank you for your patronage.  We really do appreciate all of our users and are always looking to improve our LIBs.

**Comment by FutureFutureTo** [comment]
@nd4p90x Alright thanks - thanks for looking into it. I'll await it

**Comment by nd4p90x** [comment]
@FutureFutureTo Here you go https://github.com/segmentio/analytics-php/releases/tag/2.0.0
Thanks and LMK if I can do anything else for you
