### ISSUE TITLE
timestamp : microseconds turned into microseconds

### ISSUE THREAD

**Issue by Possum3D** [segmentio/analytics-php#41]
Ey there,

it seems that we cannot microtimestamp events when using the library; It does not crash, it just converts into seconds.

After some investigation, I seem to have found where 'timestamp' is turned from microtime(true) to rounded value in seconds:
https://github.com/segmentio/analytics-php/blob/master/lib/Segment/Client.php#L134%20#L135

I believe the iso8601 removes the microtime precision. 

It makes sense, in that, when we use the file consumer, the send command would currently crash if it were microseconds:
https://github.com/segmentio/analytics-php/blob/master/send.php#L72

strtotime would not take microseconds I believe.

However, this would really be most helpful to be able to pass microseconds!

**Comment by calvinfo** [comment]
Yeah we should definitely have a way of allowing microseconds to be passed in. I think just swapping `time` for `microtime` and adding an update parsing function should do it. We'll probably want to bump major version for it so that people passing in timestamps or using the file consumer know that they'll require a new format. Might also want the file consumer to support both formats so users can upgrade while the files still exist on the system.

cc @yields

**Comment by sperand-io** [comment]
just to reflect the concerns of another customer:

>We wish to have all our events in the right order, as this is important for funnel analysis. Events sent sever-side (php) have a micro timestamp on our side, but it seems your php library does not support. Hence the events might end up in the wrong order (ex : activated before signed up), particularly if batched (:/), not to mention collision with microtimestamps of the front end js events !!

@calvinfo @yields

**Comment by yields** [comment]
should be fixed in db24fa9a2e1110570c338fea7a6f46bbb7ef105c, it's backwards compatible too so you can install `1.1.0`.

**Comment by Possum3D** [comment]
awesome! Gonna try this asap.

**Comment by Possum3D** [comment]
awesome, thks!
