### ISSUE TITLE
Why use exec() instead of PHP's cURL functions?

### ISSUE THREAD

**Issue by tnorthcutt** [segmentio/analytics-php#55]
I'm using the Segment PHP library in a project, but the host we're on has `exec()`disabled for security reasons. Is there any particular reason you're using `exec()` [here](https://github.com/segmentio/analytics-php/blob/c01a2c32286c9c7cd5d7f324d17bbbefff0946ac/lib/Segment/Consumer/ForkCurl.php#L48) instead of [PHP's cURL functions](https://secure.php.net/manual/en/ref.curl.php)?

**Comment by calvinfo** [comment]
It's been a little while since I last looked, but the main things I
remember:

- we chose to fork since it cuts down on the latency vs making a call to
our servers during the request lifecycle
- the curl multi handler had some issues in my testing

We'd totally accept a PR though, I think it's a bit more bulletproof than
forking, and would actually end up as a nicer default.
