### ISSUE TITLE
Custom consumer

### ISSUE THREAD

**Issue by dpgover** [segmentio/analytics-php#61]
I think it would be a good idea to be able to make my own consumer.

In my current app I need to write and read the logs from Amazon S3, from two different frontend servers.

**Comment by hankim813** [comment]
@calvinfo could you chime in here?

**Comment by calvinfo** [comment]
It sounds reasonable to me, we could definitely support this pretty easily, are you already forking this and doing this on your own @dpgover?

We do offer an S3 integration internally so that you can accomplish this same thing!

**Comment by dpgover** [comment]
No, in fact, I'm using another library because of this.

**Comment by hankim813** [comment]
@calvinfo I'll add this feature request to JIRA!

**Comment by f2prateek** [comment]
I'm not entirely sure what the request is here and the action should be. @dpgover @calvinfo can you clarify? It sounds like @dpgover is looking to consume events sent from analytics-php on the other end of our API (and write them to s3)? That seems a bit out of scope for analytics-php.

**Comment by f2prateek** [comment]
Oh I see, maybe this is referring to being able to plug in a custom implementation of the consumer type (https://github.com/segmentio/analytics-php/blob/master/lib/Segment/Consumer.php) rather than just be limited to the built in ones.

This seems reasonable.

Tracking internally in JIRA as well — https://segment.atlassian.net/browse/LIB-141.
