### ISSUE TITLE
An option to send a batch of identify, group, track, page and screen requests

### ISSUE THREAD

**Issue by django23** [segmentio/analytics-php#96]
https://segment.com/docs/sources/server/http/#batch

> Batch
> The batch method lets you send a series of identify, group, track, page and screen requests in a single batch, saving on outbound requests. Our server-side and mobile sources make use of this method automatically for higher performance.
> 
> There is a maximum of 500kb per batch request and 32kb per call.
> 
> Here’s the what the batch request signature looks like:
> 
> `POST https://api.segment.io/v1/batch`

**Comment by f2prateek** [comment]
It's not clear what the issue is for?

The library handles batching internally already. It queues messages https://github.com/segmentio/analytics-php/blob/master/lib/Segment/QueueConsumer.php and uploads them to api.segment.io/v1/import (which is an alias for v1/batch) https://github.com/segmentio/analytics-php/blob/master/lib/Segment/Consumer/LibCurl.php#L37-L40.

**Comment by django23** [comment]
Oh well if it fixes it internally, ignore my message completely. Thanks!
